import "./globals.css";
import { Inter } from "next/font/google";

import Provider from "../../components/Provider";
import Nav from "../../components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Outreacher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${inter.className} h-screen flex flex-col`}>
          <Nav />
          {children}
        </body>
      </Provider>
    </html>
  );
}
