import "../../styles/globals.css";
import { Inter } from "next/font/google";

import Provider from "../../components/Provider";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Outreacher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${inter.className} h-screen`}>
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </Provider>
    </html>
  );
}
